title: My awesome title
author: Kylre
email: Kylresharpftw@gmail.com
description: > # this means to ignore newlines until "baseurl:"
  This is homework, and a temporary filler.
# social links
twitter_username: @Idon'thaveone  
github_username:  Kylre
theme: minima
show_excerpts: true # set to false to remove excerpts on the homepage
