Theme: manima
title: I need sleep but I must code
author: GitHub User
email: your-email@domain.com
description: > I'm a noob with this coding lingo

# social links
twitter_username: your-twitter-handle
github_username:  your-github-handle

show_excerpts: true # set to false to remove excerpts on the homepage
